version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: morse-rabbitmq
        ports:
            - '5672:5672' # AMQP port
            - '15672:15672' # Management UI port
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin123
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        networks:
            - morse-network
        restart: unless-stopped
        healthcheck:
            test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
            interval: 30s
            timeout: 30s
            retries: 3

    morse-front:
        image: angysquirrel/morse-front:latest
        container_name: morse-front
        ports:
            - '85:80'
        depends_on:
            - rabbitmq
            - morse-back
        networks:
            - morse-network

    morse-back:
        image: angysquirrel/morse-back:latest
        container_name: morse-back
        ports:
            - '3001:3001'
        depends_on:
            - rabbitmq
        environment:
            RABBITMQ_URL: 'amqp://admin:admin123@192.168.1.11:5672'
            DATABASE_URL: 'file:./prisma/dev.db'
            JWT_SECRET: '6f8e2b1c7a9d4e5f3c2b8a7e6d5c4b3a1f0e9d8c7b6a5e4d3c2b1a0f9e8d7c6'
            CORS_ORIGIN: 'http://192.168.1.11:85'
        volumes:
            - morse-back-db:/app/prisma/dev.db
        restart: unless-stopped
        networks:
            - morse-network

volumes:
    rabbitmq_data:
    morse-back-db:

networks:
    morse-network:
        driver: bridge
